[package]
name = "turtle2rdf"
version = "0.1.0"
edition = "2021"

[dependencies]
rio_api = "0.7.1"
rio_turtle = "0.7.1"
tera = "1.15.0"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.3.2"
url = "2.5.2"
clap = { version = "4.0", features = ["derive"] }

